FROM ubuntu:18.04

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository -y ppa:ethereum/ethereum
RUN apt-get update
RUN apt-get install -y ethereum

CMD geth --datadir=/rinkeby/chaindata --rinkeby --rpc --rpcapi db,eth,net,web3,personal --cache 24576 --allow-insecure-unlock
