FROM ubuntu:18.04

RUN apt-get update && apt-get install -y python3 python3-pip python python-pip

RUN pip3 install web3 flask gunicorn flask-cors

COPY server/app.py .
COPY server/config.ini .
COPY build/contracts/UserList.json .

COPY keystore/certs/fullchain.pem .
COPY keystore/certs/privkey.pem .
COPY keystore/certs/chain.pem .

CMD gunicorn -w 4 -b 0.0.0.0:80 --ca-certs=chain.pem app:app
