version: '3'
services:
  rinkeby:
    build:
      context: .
      dockerfile: Dockerfile.rinkeby
    ports:
      - "30303:30303"
      - "30301:30301"
      - "8545:8545"
    volumes:
      - /rinkeby:/rinkeby
  webserver:
    build:
      context: .
      dockerfile: Dockerfile.webserver
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /rinkeby:/rinkeby
