var triviaQuestions = [
  {
    question : "How many farmers grow coffee globally (millions)?",
    image : "images/parchiment.jpg",
    imageName :"Coffee parchiment",
    answer : ["10","15","20"],
    correctAnswer : "a",
    context : "The global coffee market is the second largest globally traded commodity after oil. The value of the global coffee market is over $20B USD, yet 90% of coffee farmers earn less than $Y/day.",
  },
  {
    question : "In how many countries does TechnoServe have entrepreneurship training programs?",
    image : "images/smartDuka.jpg",
    imageName : "Duka Owner",
    answer : ["13","19","24"],
    correctAnswer : "c",
    context : "TechnoServe started its Entrepreneurship training program in 2011 in South America, and now runs entrepreneurship training programs in 24 countries, training over 40,000 people each year.",
  },
  {
    question : "What is one solution for 'remote sensing?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["SMS", "Drones", "Distributed Applications"],
    correctAnswer : "b",
    context : "context message",
  },
  {
    question : "In how many countries does TechnoServe operate?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["17", "29", "48"],
    correctAnswer : "b",
    context : "context message",
  },
  {
    question : "How many people saw their incomes increase as a result of TechnoServe's work?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["85,000 people", "557,000 people", "8 million people"],
    correctAnswer : "b",
    context : "context message",
  },
  {
    question : "What technology can be used to implement smart contracts and improve supply chain transparency in low trust environments?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["Blockchain", "Mobile Money", "Remote Sensing"],
    correctAnswer : "a",
    context : "context message",
  },
  {
    question : "What percent of coffee farmers, globally, has TechnoServed trained with better agronomy practices to improve their incomes?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["3 percent", "5 percent", "6 percent"],
    correctAnswer : "c",
    context : "context message",
  },
  {
    question : "What percentage of the entrepreneurs TechnoServe works with are women?",
    image : "images/smartDuka.jpg",
    imageName : "Duka owner",
    answer : ["39%", "45%", "58%"],
    correctAnswer : "c",
    context : "context message",
  },
  {
    question : "What technology can be used to classify aerial images, to identify whether farmers have implemented agronomic best practices?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["Machine Learning", "Virtual Reality", "Internet of Things (IoT)"],
    correctAnswer : "a",
    context : "context message",
  },
  {
    question : "How many TechnoServe Fellow alums are there worldwide, since the TechnoServe Fellows program started in 2000?",
    image : "images/drone.jpg",
    imageName : "Drone",
    answer : ["1300", "900", "490"],
    correctAnswer : "a",
    context : "context message",
  }
];
