var triviaQuestions = [
  {
    question : "How many farmers grow coffee globally?",
    image : "/images/small_coffee_growers_small.jpg",
    imageName :"Coffee growers",
    answer : ["3 million","12 million","25 million"],
    correctAnswer : "b",
    context : "The global coffee market is the second largest globally traded commodity after oil. The value of the global coffee market is over $20B USD, yet 80% of small holder farmers earn less than $2/day.",
  },
  {
    question : "In how many countries does TechnoServe have entrepreneurship training programs?",
    image : "/images/entrepreneurship_training_small.jpg",
    imageName : "Entrepreneurship training",
    answer : ["13","19","24"],
    correctAnswer : "c",
    context : "TechnoServe started its Entrepreneurship training program in 2011 in South America, and now runs entrepreneurship programs in 24 countries, training over 40,000 people each year.",
  },
  {
    question : "What is one solution for 'remote sensing?",
    image : "/images/drone_small.jpg",
    imageName : "Drone",
    answer : ["SMS", "Drones", "Distributed Applications"],
    correctAnswer : "b",
    context : "TechnoServe has piloted drone technology in Mozambique and Uganda, and plans to use satelites and drones to decrease the cost of collecting farm yield data.",
  },
  {
    question : "In how many countries does TechnoServe operate?",
    image : "/images/women_entrepreneurs_small.jpg",
    imageName : "Women entrepreneur",
    answer : ["17", "29", "48"],
    correctAnswer : "b",
    context : "TechnoServe has 1200 employees in 29 countries, with operations in Latin America, Africa, and India.",
  },
  {
    question : "What are potential benefits of using blockchain to improve traceability in the cashew supply chain?",
    image : "/images/cashew_processing_small.jpg",
    imageName : "Cashew processing",
    answer : ["Transparency and tax revenue", " Farmer incomes", "Transparency, tax revenue, and farmer incomes"],
    correctAnswer : "c",
    context : "Improved transparency in the $10 billion global cashew sector could boost small farmer incomes and also increase tax revenue for agricultural programs.",
  },
  {
    question : "What technology can be used to implement smart contracts and improve supply chain transparency in low trust environments?",
    image : "/images/blockchain_smart_contracts_small.jpg",
    imageName : "Coffee wet mill with smartphones",
    answer : ["Blockchain", "Mobile Money", "Remote Sensing"],
    correctAnswer : "a",
    context : "With better price and supply chain data, buyers can make better decisions that can increase prices for smallholder farmers. ",
  },
  {
    question : "How many coffee farmers has TechnoServed trained with better agronomy practices to improve their incomes?",
    image : "/images/small_coffee_growers_small.jpg",
    imageName : "Drone",
    answer : ["200,000", "400,000", "6 million"],
    correctAnswer : "c",
    context : "TechnoServe has trained 400,000 small coffee farmers, increasing their incomes by 30-50%.",
  },
  {
    question : "What percentage of the entrepreneurs TechnoServe works with are women?",
    image : "/images/smartDuka_small.jpg",
    imageName : "Duka owner",
    answer : ["39%", "45%", "58%"],
    correctAnswer : "c",
    context : "TechnoServe proactively engages women in all of its training programs. 58% of participants in its entrepreneurship programs were women.",
  },
  {
    question : "What technology can be used to classify aerial images as a cost-effective way to identify thousands of farmers who need agronomic training?",
    image : "/images/remote_sensing_small.jpg",
    imageName : "Aerial image",
    answer : ["Machine Learning", "Virtual Reality", "Internet of Things (IoT)"],
    correctAnswer : "a",
    context : "Machine learning can be used in combination with remote sensing to effectively target millions of farmers in need of training.",
  },
  {
    question : "What technology is TechnoServe using to scale up entrepreneurship training programs?",
    image : "/images/distance_learning_small.jpg",
    imageName : "Man at computer",
    answer : ["Distance Learning", "Remote Sensing", "Blockchain"],
    correctAnswer : "a",
    context : "E-learning platforms, remote mentoring, and other techologies can dramatically scale the impact of entrepreneurship programs.",
  }
];
